### user router
GET http://localhost:8000/v1/user

### register
POST http://localhost:8000/v1/user
Content-Type: application/json

{
    "name":"Himanshu",
    "company":"Company",
    "address":"12222 sdds",
    "phone":123456789,
    "email":"a@a.com",
    "password":"12345678"
}

### login
POST http://localhost:8000/v1/user/login
Content-Type: application/json

{
    "email":"a@a.com",
    "password":"12345678"
}

### get a user profile
GET http://localhost:8000/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiYUBhLmNvbSJ9LCJpYXQiOjE2NjQxNjc5NzYsImV4cCI6MTY2NDE2ODg3Nn0.QKhhq4FbnbeQG3bieorpfJDjX9Rbwea5FsLyUyi76zE



